name: Docker Image Build and Push

on:
  workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Fetch all history and tags

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get latest release tag (if available)
      id: get_latest_tag
      run: |
        latest_tag=$(git describe --tags --abbrev=0 2>/dev/null)
        if [[ -n "$latest_tag" ]]; then
          echo "::set-output name=tag::$latest_tag"
        else
          echo "::set-output name=tag:latest" # Default to 'latest' if no tag found
        fi

    - name: Extract metadata (tags, labels) for Docker builds
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}
        tags: |
          type=semver,prefix=v # Always generate semver tags
          type=raw,value=${{ steps.get_latest_tag.outputs.tag }},enable=${{ github.event_name != 'release' }} # Use latest tag or latest on manual trigger
          type=ref,event=release,prefix=v,enable=${{ github.event_name == 'release' }} # Only create release tag on release event

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}