name: Docker Image Build and Push

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history and tags

      - name: Get latest release tag
        id: get-tag
        run: echo "TAG_NAME=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push multi-arch Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/gobuilder:${{ env.TAG_NAME }}
            ${{ secrets.DOCKERHUB_USERNAME }}/gobuilder:latest
          labels: |
            org.opencontainers.image.source=https://github.com/shammishailaj/gobuilder
