name: Create GitHub Release

on:
    push:
      tags:
        - '*' # Triggers on any tag push
    workflow_dispatch: # Allows manual triggering from GitHub UI

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Get current date and time
        id: date
        run: echo "date=$(date +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV

      - name: Determine release version
        id: version
        run: |
          VERSION=$(cat VERSION)
          echo "tag=$VERSION" >> $GITHUB_ENV
          
      - name: Read Release Text
        id: rnotes
        run: |
          RNOTES=$(cat RELEASE.md)
          echo "rnotesdata=$RNOTES" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ env.tag }}
          release_name: Release ${{ env.tag }}
          body: |
            Release notes:
            ---
            Created At ${{ steps.date.outputs.date }}
            ---
            ${{ steps.rnotes.outputs.rnotesdata}}
          draft: false
          prerelease: false